"use client";

import { useState, useEffect } from "react";
import { createPortal } from "react-dom";

const DISCLAIMER_KEY = "internlabs_disclaimer_accepted_v2";

const POINTS = [
  {
    icon: "🚫",
    title: "No AI-generated submissions",
    body: "Do not copy, paste, or submit work generated by AI tools (ChatGPT, Copilot, etc.). Your documents must reflect your own understanding and effort. AI-generated content is automatically flagged during review and will be rejected immediately — affecting your internship evaluation.",
  },
  {
    icon: "📄",
    title: "Submit documents accurately",
    body: "Upload only complete, honest, and relevant documents for each stage. Incomplete, mismatched, or falsified submissions will be rejected and may result in a stage being locked until a correct revision is provided. Each submission is reviewed against the stage deliverable.",
  },
  {
    icon: "💬",
    title: "Maintain professional language",
    body: "All chat messages with your mentor are logged. Use respectful, professional language at all times. Off-topic conversations, inappropriate remarks, or abusive language are strictly prohibited and may lead to account review.",
  },
  {
    icon: "🔒",
    title: "Keep project content confidential",
    body: "All project briefs, company information, stage details, and mentor feedback shared inside this workspace are confidential. Do not share them externally — in any form — without explicit written permission.",
  },
  {
    icon: "⏱️",
    title: "Respect phase timelines",
    body: "Each phase has a recommended timeline. Falling significantly behind without communication with your mentor may impact your final assessment. If you need more time, inform your mentor through the chat.",
  },
];

export default function DisclaimerModal({ onAccept }) {
  const [mounted, setMounted] = useState(false);
  const [checked, setChecked] = useState(false);
  const [shaking, setShaking] = useState(false);

  useEffect(() => { setMounted(true); }, []);

  function handleAccept() {
    if (!checked) {
      setShaking(true);
      setTimeout(() => setShaking(false), 500);
      return;
    }
    try { localStorage.setItem(DISCLAIMER_KEY, "1"); } catch {}
    onAccept();
  }

  if (!mounted) return null;

  return createPortal(
    <div
      style={{
        position: "fixed", inset: 0, zIndex: 99999,
        display: "flex", alignItems: "center", justifyContent: "center",
        padding: "16px",
        background: "rgba(6,6,10,0.82)",
        backdropFilter: "blur(4px)",
      }}
    >
      <div style={{
        width: "100%", maxWidth: 680,
        borderRadius: 24,
        overflow: "hidden",
        background: "white",
        border: "1.5px solid rgba(249,115,22,0.2)",
        boxShadow: "0 40px 80px -24px rgba(15,23,42,0.7), 0 0 0 1px rgba(249,115,22,0.08)",
        maxHeight: "90vh",
        display: "flex",
        flexDirection: "column",
      }}>

        {/* Header */}
        <div style={{
          background: "linear-gradient(135deg, #1a1311 0%, #2d1a0e 100%)",
          padding: "20px 24px 18px",
          flexShrink: 0,
        }}>
          <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
            <div style={{
              width: 42, height: 42, borderRadius: 12, flexShrink: 0,
              background: "linear-gradient(135deg, #f97316, #fb923c)",
              display: "flex", alignItems: "center", justifyContent: "center",
              fontSize: "1.3rem",
              boxShadow: "0 4px 14px -4px rgba(249,115,22,0.6)",
            }}>
              📋
            </div>
            <div>
              <p style={{
                fontSize: "0.58rem", fontWeight: 900,
                textTransform: "uppercase", letterSpacing: "0.2em",
                color: "#f97316", margin: "0 0 3px",
              }}>
                Before you begin
              </p>
              <h2 style={{
                fontSize: "1.05rem", fontWeight: 900,
                color: "white", margin: 0, lineHeight: 1.2,
              }}>
                Internship Code of Conduct
              </h2>
            </div>
          </div>
          <p style={{
            fontSize: "0.75rem", fontWeight: 500,
            color: "rgba(255,255,255,0.6)", margin: "12px 0 0",
            lineHeight: 1.6,
          }}>
            Please read and acknowledge the following guidelines carefully. You must agree before accessing your workspace.
          </p>
        </div>

        {/* Scrollable points */}
        <div style={{
          overflowY: "auto", flex: 1,
          padding: "0 24px",
        }}>
          {POINTS.map((pt, i) => (
            <div key={i} style={{
              display: "flex", gap: 14,
              padding: "16px 0",
              borderBottom: i < POINTS.length - 1 ? "1px solid #f1f5f9" : "none",
            }}>
              <div style={{
                width: 36, height: 36, borderRadius: 10, flexShrink: 0,
                background: "#fff7ed",
                border: "1px solid rgba(249,115,22,0.18)",
                display: "flex", alignItems: "center", justifyContent: "center",
                fontSize: "1.05rem",
                marginTop: 1,
              }}>
                {pt.icon}
              </div>
              <div>
                <p style={{
                  fontSize: "0.82rem", fontWeight: 900,
                  color: "#1e293b", margin: "0 0 4px",
                }}>
                  {pt.title}
                </p>
                <p style={{
                  fontSize: "0.74rem", fontWeight: 500,
                  color: "#64748b", margin: 0, lineHeight: 1.65,
                }}>
                  {pt.body}
                </p>
              </div>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div style={{
          padding: "16px 24px 20px",
          borderTop: "1px solid #f1f5f9",
          background: "#fafafa",
          flexShrink: 0,
        }}>
          {/* Checkbox */}
          <label
            style={{
              display: "flex", alignItems: "flex-start", gap: 10,
              cursor: "pointer", marginBottom: 16,
              animation: shaking ? "shake 0.45s ease" : "none",
            }}
          >
            <input
              type="checkbox"
              checked={checked}
              onChange={(e) => setChecked(e.target.checked)}
              style={{
                width: 18, height: 18, marginTop: 1, flexShrink: 0,
                accentColor: "#f97316", cursor: "pointer",
              }}
            />
            <span style={{
              fontSize: "0.76rem", fontWeight: 600,
              color: checked ? "#1e293b" : "#64748b",
              lineHeight: 1.55,
              transition: "color 0.2s",
            }}>
              I have read and understood all the guidelines above. I agree to follow the Internship Code of Conduct throughout this programme.
            </span>
          </label>

          {/* Button */}
          <button
            type="button"
            onClick={handleAccept}
            style={{
              width: "100%", height: 44,
              borderRadius: 12, border: "none",
              background: checked
                ? "linear-gradient(135deg, #f97316, #fb923c)"
                : "#e2e8f0",
              color: checked ? "white" : "#94a3b8",
              fontSize: "0.85rem", fontWeight: 900,
              cursor: checked ? "pointer" : "not-allowed",
              boxShadow: checked ? "0 6px 20px -6px rgba(249,115,22,0.65)" : "none",
              transition: "background 0.25s, color 0.25s, box-shadow 0.25s",
              letterSpacing: "0.01em",
            }}
          >
            {checked ? "I Agree & Enter Workspace →" : "Check the box above to continue"}
          </button>
        </div>
      </div>

      <style>{`
        @keyframes shake {
          0%,100%{transform:translateX(0)}
          20%{transform:translateX(-6px)}
          40%{transform:translateX(6px)}
          60%{transform:translateX(-4px)}
          80%{transform:translateX(4px)}
        }
      `}</style>
    </div>,
    document.body
  );
}

export function disclaimerAccepted() {
  try { return Boolean(localStorage.getItem("internlabs_disclaimer_accepted_v2")); } catch { return false; }
}
