-- Add payment tracking + access gating
-- Date: 2026-04-30

ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS has_paid BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS paid_amount_paisa INTEGER;

ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS paid_currency VARCHAR(10) DEFAULT 'INR';

ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS paid_at TIMESTAMPTZ;

ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS payment_provider VARCHAR(30);

ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS payment_status VARCHAR(30);

ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS payment_reference VARCHAR(120);

CREATE INDEX IF NOT EXISTS ix_users_has_paid ON users(has_paid);
