ALTER TABLE project_stage_progress
  ADD COLUMN IF NOT EXISTS document_required BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS document_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS document_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS document_public_id TEXT NOT NULL DEFAULT '';
